COPY OMDB_BUSINESS_CAST FROM "./export_elt/gold_business_graph_node_cast.json"
COPY OMDB_BUSINESS_CATEGORY FROM "./export_elt/gold_business_graph_node_category.json"
COPY OMDB_BUSINESS_CHARACTER FROM "./export_elt/gold_business_graph_node_character.json"
COPY OMDB_BUSINESS_CONTENT FROM "./export_elt/gold_business_graph_node_content.json"
COPY OMDB_BUSINESS_IMAGE FROM "./export_elt/gold_business_graph_node_image.json"
COPY OMDB_BUSINESS_JOB FROM "./export_elt/gold_business_graph_node_job.json"
COPY OMDB_BUSINESS_PERSON FROM "./export_elt/gold_business_graph_node_person.json"